### ISSUE TITLE
随机端口如何在docker容器中映射？

### ISSUE THREAD

**Issue by hexxv** [dobyte/due#13]
server.NewServer() 用到了 xnet.ParseAddr() , 用到了随机端口。
我想问：如果我将项目打包成docker镜像，容器化运行时，如何映射容器与宿主机的端口？

**Comment by dobyte** [comment]
docker中使用的话，可以改成固定端口

**Comment by hexxv** [comment]
谢谢，我现在知道了。固定端口是一种方式，还有一种就是docker的 host网络模式 也可以
