### ISSUE TITLE
增加自定义rpc服务，服务间进行rpc调用。

### ISSUE THREAD

**Issue by wlf92** [dobyte/due#2]
1 在路由的基础上，可增加自定义rpc服务，个人习惯是grpc，具体看大佬的设计哈。
2 rpc连接池管理，增加复用。
3 rpc调用可设置重试次数，避免网络波动。

**Comment by wlf92** [comment]
大佬，催更啦。另外请教下，如果不用rpc，你们是如何解决rpc调用的问题的？
因为之前听你说了下，主要针对过往经验的痛点的设计的这么一个框架。rpc调用应该比较迫切的功能点吧。
另外，方便留一下联系方式么？

**Comment by wlf92** [comment]
额，mongo无缘。

**Comment by dobyte** [comment]
![image](https://user-images.githubusercontent.com/42379346/202679703-d2af5a2d-cd4e-4fd1-9872-96a0af8a83bf.png)

**Comment by dobyte** [comment]
加我微信，我把你拉到群里面，后期可以一起交流学习
